--1. Klauzula ROLLUP - celem wyliczenia srednich cen uslug,kosztów materialu oraz zysku dla poszczególnego typu zlecenia.

SELECT NVL(TO_CHAR(ZLECENIE.TYP_ZLECENIA_ID_TYPU),'SREDNIA OGOLNA:') AS "TYP ZLECENIA",  ROUND(AVG(ZLECENIE.CENA_USLUGI),2) AS "CENA USLUGI", 
ROUND(AVG(ZLECENIE.KOSZT_MATERIALOW),2) AS "KOSZT MATERIALU", ROUND(AVG(ZLECENIE.ZYSK),2) AS "ZYSK"
FROM ZLECENIE GROUP BY ROLLUP(ZLECENIE.TYP_ZLECENIA_ID_TYPU);

--2. Klauzula CUBE - celem wyliczenia sredniego zysku i czasu trwania uslugi dla danego typu zlecenia wykonywanego przez danego pracownika.

SELECT NVL(TO_CHAR(ZLECENIE.PRACOWNIK_ID_PRACOWNIKA),' ') AS "ID PRACOWNIKA", 
NVL(TO_CHAR(ZLECENIE.TYP_ZLECENIA_ID_TYPU),' ') AS "TYP ZLECENIA", 
ROUND(AVG(ZLECENIE.ZYSK),2) AS "ZYSK", ROUND(AVG(ZLECENIE.CZAS_TRWANIA)) AS "CZAS TRWANIA (W DNIACH)" 
FROM ZLECENIE GROUP BY CUBE(ZLECENIE.PRACOWNIK_ID_PRACOWNIKA, ZLECENIE.TYP_ZLECENIA_ID_TYPU);

--3. Klazula GROUPING SETS - celem wyliczenia, ile dany klient zaplacil za wszystkie uslugi w firmie wykonywane przez danego pracownika.

SELECT NVL(TO_CHAR(ZLECENIE.KLIENT_ID_KLIENTA),' ') AS "KLIENT", NVL(TO_CHAR(ZLECENIE.TYP_ZLECENIA_ID_TYPU),' ') AS "TYP USLUGI", 
NVL(TO_CHAR(ZLECENIE.PRACOWNIK_ID_PRACOWNIKA),' ') AS "ID PRACOWNIKA", SUM(ZLECENIE.ZYSK) AS "ZYSK"
FROM ZLECENIE GROUP BY GROUPING SETS(ZLECENIE.KLIENT_ID_KLIENTA, ZLECENIE.TYP_ZLECENIA_ID_TYPU, ZLECENIE.PRACOWNIK_ID_PRACOWNIKA)
ORDER BY ZLECENIE.KLIENT_ID_KLIENTA,ZLECENIE.TYP_ZLECENIA_ID_TYPU,ZLECENIE.PRACOWNIK_ID_PRACOWNIKA;

--4. Partycjonowanie - PARTITION BY.

SELECT DISTINCT ZLECENIE.TYP_ZLECENIA_ID_TYPU AS "TYP ZLECENIA", ZLECENIE.CZAS_TRWANIA AS "CZAS TRWANIA (DNI)", ROUND(SUM(ZLECENIE.ZYSK) OVER (PARTITION BY ZLECENIE.TYP_ZLECENIA_ID_TYPU, ZLECENIE.CZAS_TRWANIA),2) AS "ZYSK", 
TO_CHAR(ROUND((100*SUM(ZLECENIE.ZYSK) OVER (PARTITION BY ZLECENIE.TYP_ZLECENIA_ID_TYPU, ZLECENIE.CZAS_TRWANIA)/SUM(ZLECENIE.ZYSK) OVER (PARTITION BY ZLECENIE.TYP_ZLECENIA_ID_TYPU)),2)||'%') AS "UDZIAL % W ZYSKU DLA TYPU",
ROUND(SUM(ZLECENIE.CENA_USLUGI) OVER (PARTITION BY ZLECENIE.TYP_ZLECENIA_ID_TYPU,ZLECENIE.CZAS_TRWANIA),2) AS "CENA USLUGI",
TO_CHAR(ROUND((100*SUM(ZLECENIE.CENA_USLUGI) OVER (PARTITION BY ZLECENIE.TYP_ZLECENIA_ID_TYPU, ZLECENIE.CZAS_TRWANIA)/SUM(ZLECENIE.CENA_USLUGI) OVER (PARTITION BY ZLECENIE.TYP_ZLECENIA_ID_TYPU)),2)||'%') AS "UDZIAL % W CENIE DLA TYPU",
ROUND(SUM(ZLECENIE.KOSZT_MATERIALOW) OVER (PARTITION BY ZLECENIE.TYP_ZLECENIA_ID_TYPU,ZLECENIE.CZAS_TRWANIA),2) AS "KOSZT MATERIALU",
TO_CHAR(ROUND((100*SUM(ZLECENIE.KOSZT_MATERIALOW) OVER (PARTITION BY ZLECENIE.TYP_ZLECENIA_ID_TYPU, ZLECENIE.CZAS_TRWANIA)/SUM(ZLECENIE.KOSZT_MATERIALOW) OVER (PARTITION BY ZLECENIE.TYP_ZLECENIA_ID_TYPU)),2)||'%') AS "UDZIAL % W MATERIALE DLA TYPU"
FROM ZLECENIE ORDER BY ZLECENIE.TYP_ZLECENIA_ID_TYPU, ZLECENIE.CZAS_TRWANIA;

SELECT DISTINCT ROK.NUMER AS "ROK", TYP_PRODUKTU.ID_TYPU AS "TYP PRODUKTU", TYP_PRODUKTU.NAZWA AS "NAZWA PRODUKTU", STANOWISKO.NAZWA AS "STANOWISKO", PRACOWNIK.NAZWISKO AS "NAZWISKO", 
ROUND(COUNT(ZLECENIE.ID_ZLECENIA) OVER (PARTITION BY ROK.NUMER,TYP_PRODUKTU.ID_TYPU,TYP_PRODUKTU.NAZWA,STANOWISKO.NAZWA,PRACOWNIK.NAZWISKO),2) AS "ILOSC ZLECEN",
TO_CHAR(ROUND((100*COUNT(ZLECENIE.ID_ZLECENIA) OVER (PARTITION BY ROK.NUMER,TYP_PRODUKTU.ID_TYPU,TYP_PRODUKTU.NAZWA,STANOWISKO.NAZWA,PRACOWNIK.NAZWISKO)/COUNT(ZLECENIE.ID_ZLECENIA) OVER (PARTITION BY ROK.NUMER,TYP_PRODUKTU.ID_TYPU)),2)||'%') AS "UDZIAL % ROCZNY DLA TYPU"
FROM ZLECENIE,TYP_PRODUKTU,ROK,DATA,PRACOWNIK,TYP_ZLECENIA,STANOWISKO WHERE ROK.ID_ROKU = DATA.ROK_ID_ROKU AND DATA.ID_DATY = ZLECENIE.DATA_ID_DATY AND STANOWISKO.ID_STANOWISKO = PRACOWNIK.STANOWISKO_ID_STANOWISKO 
AND PRACOWNIK.ID_PRACOWNIKA = ZLECENIE.PRACOWNIK_ID_PRACOWNIKA AND TYP_PRODUKTU.ID_TYPU = TYP_ZLECENIA.ID_TYPU AND TYP_ZLECENIA.ID_TYPU = ZLECENIE.TYP_ZLECENIA_ID_TYPU
ORDER BY ROK.NUMER , TYP_PRODUKTU.ID_TYPU, TYP_PRODUKTU.NAZWA, STANOWISKO.NAZWA, PRACOWNIK.NAZWISKO;

--5. Okno obliczeniowe:

SELECT DISTINCT GRUPA_KLIENTELI.ID_GRUPY AS "ID GRUPY", GRUPA_KLIENTELI.NAZWA_GRUPY AS "NAZWA GRUPY", ZLECENIE.TYP_ZLECENIA_ID_TYPU AS "TYP ZLECENIA",
ROUND(SUM(ZLECENIE.CENA_USLUGI) OVER (PARTITION BY GRUPA_KLIENTELI.ID_GRUPY,ZLECENIE.TYP_ZLECENIA_ID_TYPU
ORDER BY DATA.DATA RANGE BETWEEN INTERVAL '7' DAY PRECEDING AND CURRENT ROW),2) AS "SUMA WYDATKOW" FROM GRUPA_KLIENTELI,TYP_ZLECENIA,ZLECENIE,KLIENT,DATA
WHERE GRUPA_KLIENTELI.ID_GRUPY = KLIENT.GRUPA_KLIENTELI_ID_GRUPY AND KLIENT.ID_KLIENTA = ZLECENIE.KLIENT_ID_KLIENTA AND TYP_ZLECENIA.ID_TYPU = ZLECENIE.TYP_ZLECENIA_ID_TYPU
AND DATA.ID_DATY = ZLECENIE.DATA_ID_DATY AND EXTRACT(YEAR FROM DATA.DATA) BETWEEN 2016 AND (EXTRACT(YEAR FROM SYSDATE)) ORDER BY GRUPA_KLIENTELI.ID_GRUPY;

SELECT DISTINCT STANOWISKO.ID_STANOWISKO,STANOWISKO.NAZWA, ZLECENIE.TYP_ZLECENIA_ID_TYPU , ROUND(COUNT(ZLECENIE.ID_ZLECENIA) OVER (PARTITION BY STANOWISKO.ID_STANOWISKO, ZLECENIE.TYP_ZLECENIA_ID_TYPU ORDER BY DATA.DATA
RANGE BETWEEN INTERVAL '2' YEAR PRECEDING AND INTERVAL '1' YEAR FOLLOWING),2) AS "ILOSC ZLECEN" FROM ROK,STANOWISKO,PRACOWNIK,ZLECENIE,DATA
WHERE ROK.ID_ROKU = DATA.ROK_ID_ROKU AND DATA.ID_DATY = ZLECENIE.DATA_ID_DATY AND STANOWISKO.ID_STANOWISKO = PRACOWNIK.STANOWISKO_ID_STANOWISKO AND PRACOWNIK.ID_PRACOWNIKA = ZLECENIE.PRACOWNIK_ID_PRACOWNIKA
AND EXTRACT(YEAR FROM DATA.DATA) BETWEEN 2015 AND (EXTRACT(YEAR FROM SYSDATE));

SELECT MIESIAC.NAZWA AS "MIESIAC",SUM(ZLECENIE.ZYSK) AS "ZYSK MIESIECZNY", SUM(SUM(ZLECENIE.ZYSK)) OVER (ORDER BY MIESIAC.ID_MIESIACA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS "SUMA KUMULACYJNA"
FROM ZLECENIE,MIESIAC,DATA,ROK WHERE MIESIAC.ID_MIESIACA = DATA.MIESIAC_ID_MIESIACA AND ROK.ID_ROKU = DATA.ROK_ID_ROKU AND DATA.ID_DATY = ZLECENIE.DATA_ID_DATY AND ROK.NUMER = EXTRACT(YEAR FROM SYSDATE)-1 
GROUP BY MIESIAC.NAZWA,MIESIAC.ID_MIESIACA ORDER BY MIESIAC.ID_MIESIACA;

SELECT MIESIAC.NAZWA AS "MIESIAC",SUM(ZLECENIE.ZYSK) AS "ZYSK MIESIECZNY", ROUND(AVG(SUM(ZLECENIE.ZYSK)) OVER (ORDER BY MIESIAC.ID_MIESIACA ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING),2) AS "SREDNIA CENTRALNA"
FROM ZLECENIE,MIESIAC,DATA,ROK WHERE MIESIAC.ID_MIESIACA = DATA.MIESIAC_ID_MIESIACA AND ROK.ID_ROKU = DATA.ROK_ID_ROKU AND DATA.ID_DATY = ZLECENIE.DATA_ID_DATY AND ROK.NUMER = EXTRACT(YEAR FROM SYSDATE)-1 
GROUP BY MIESIAC.NAZWA,MIESIAC.ID_MIESIACA ORDER BY MIESIAC.ID_MIESIACA;

SELECT MIESIAC.NAZWA AS "MIESIAC",SUM(ZLECENIE.ZYSK) AS "ZYSK MIESIECZNY", ROUND(AVG(SUM(ZLECENIE.ZYSK)) OVER (ORDER BY MIESIAC.ID_MIESIACA ROWS BETWEEN 3 PRECEDING AND CURRENT ROW),2) AS "SREDNIA KROCZACA"
FROM ZLECENIE,MIESIAC,DATA,ROK WHERE MIESIAC.ID_MIESIACA = DATA.MIESIAC_ID_MIESIACA AND ROK.ID_ROKU = DATA.ROK_ID_ROKU AND DATA.ID_DATY = ZLECENIE.DATA_ID_DATY AND ROK.NUMER = EXTRACT(YEAR FROM SYSDATE)-1 
GROUP BY MIESIAC.NAZWA,MIESIAC.ID_MIESIACA ORDER BY MIESIAC.ID_MIESIACA;

SELECT MIESIAC.NAZWA AS "MIESIAC", SUM(ZLECENIE.ZYSK) AS "ZYSK MIESIECZNY", FIRST_VALUE(SUM(ZLECENIE.ZYSK)) OVER (ORDER BY MIESIAC.ID_MIESIACA ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) AS "POPRZEDNI MIESIAC",
LAST_VALUE(SUM(ZLECENIE.ZYSK)) OVER (ORDER BY MIESIAC.ID_MIESIACA ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) AS "KOLEJNY MIESIAC" FROM ZLECENIE,MIESIAC,DATA,ROK 
WHERE MIESIAC.ID_MIESIACA = DATA.MIESIAC_ID_MIESIACA AND ROK.ID_ROKU = DATA.ROK_ID_ROKU AND DATA.ID_DATY = ZLECENIE.DATA_ID_DATY AND ROK.NUMER = EXTRACT(YEAR FROM SYSDATE)-1 
GROUP BY MIESIAC.NAZWA,MIESIAC.ID_MIESIACA ORDER BY MIESIAC.ID_MIESIACA;
   

--6. Ranking.

SELECT DZIEN_TYGODNIA.NAZWA AS "DZIEN", COUNT(ZLECENIE.ID_ZLECENIA) AS "ILOSC ZLECEN", DENSE_RANK() OVER (ORDER BY COUNT(ZLECENIE.ID_ZLECENIA) DESC) AS "RANKING"
FROM DZIEN_TYGODNIA,DATA,ZLECENIE WHERE DZIEN_TYGODNIA.ID_DNIA = DATA.DZIEN_TYGODNIA_ID_DNIA AND DATA.ID_DATY = ZLECENIE.DATA_ID_DATY
GROUP BY DZIEN_TYGODNIA.NAZWA;

SELECT TYP_PRODUKTU.ID_TYPU AS "ID PRODUKTU", TYP_PRODUKTU.NAZWA AS "NAZWA PRODUKTU", ZLECENIE.TYP_ZLECENIA_ID_TYPU AS "ID TYPU", TYP_ZLECENIA.NAZWA AS "NAZWA ZLECENIA", COUNT(ZLECENIE.ID_ZLECENIA) AS "ILOSC ZLECEN",
SUM(ZLECENIE.ZYSK) AS "ZYSK W ZESZLYM ROKU", DENSE_RANK() OVER (ORDER BY SUM(ZLECENIE.ZYSK) DESC) AS "RANKING" FROM ZLECENIE,TYP_ZLECENIA,ROK,DATA,TYP_PRODUKTU
WHERE TYP_PRODUKTU.ID_TYPU = TYP_ZLECENIA.TYP_PRODUKTU_ID_TYPU AND TYP_ZLECENIA.ID_TYPU = ZLECENIE.TYP_ZLECENIA_ID_TYPU AND ROK.ID_ROKU = DATA.ROK_ID_ROKU AND DATA.ID_DATY = ZLECENIE.DATA_ID_DATY
AND ROK.NUMER = (EXTRACT(YEAR FROM SYSDATE)-1) GROUP BY ZLECENIE.TYP_ZLECENIA_ID_TYPU, TYP_ZLECENIA.NAZWA, TYP_PRODUKTU.ID_TYPU, TYP_PRODUKTU.NAZWA;

SELECT ROK.NUMER AS "ROK",ZLECENIE.TYP_ZLECENIA_ID_TYPU AS "ID TYPU" ,TYP_ZLECENIA.NAZWA AS "NAZWA ZLECENIA",COUNT(ZLECENIE.KLIENT_ID_KLIENTA) AS "ILOSC KLIENTOW",
DENSE_RANK() OVER (ORDER BY COUNT(ZLECENIE.KLIENT_ID_KLIENTA) DESC) AS "RANKING" FROM ZLECENIE,TYP_ZLECENIA,ROK,DATA
WHERE TYP_ZLECENIA.ID_TYPU = ZLECENIE.TYP_ZLECENIA_ID_TYPU AND ROK.ID_ROKU = DATA.ROK_ID_ROKU AND DATA.ID_DATY = ZLECENIE.DATA_ID_DATY GROUP BY ROK.NUMER,ZLECENIE.TYP_ZLECENIA_ID_TYPU,TYP_ZLECENIA.NAZWA;
