CREATE TABLE DATA
  (
    ID_DATY                NUMBER (7) NOT NULL ,
    DZIEN_TYGODNIA_ID_DNIA NUMBER (7) NOT NULL ,
    MIESIAC_ID_MIESIACA    NUMBER (7) NOT NULL ,
    KWARTAL_ID_KWARTALU    NUMBER (7) NOT NULL ,
    ROK_ID_ROKU            NUMBER (7) NOT NULL ,
    DATA                   DATE
  ) ;
ALTER TABLE DATA ADD CONSTRAINT DATA_PK PRIMARY KEY ( ID_DATY ) ;


CREATE TABLE DZIEN_TYGODNIA
  (
    ID_DNIA NUMBER (7) NOT NULL ,
    NAZWA   VARCHAR2 (200)
  ) ;
ALTER TABLE DZIEN_TYGODNIA ADD CONSTRAINT DZIEN_TYGODNIA_PK PRIMARY KEY ( ID_DNIA ) ;


CREATE TABLE GRUPA_KLIENTELI
  (
    ID_GRUPY    NUMBER (7) NOT NULL ,
    NAZWA_GRUPY VARCHAR2 (200)
  ) ;
ALTER TABLE GRUPA_KLIENTELI ADD CONSTRAINT GRUPA_KLIENTELI_PK PRIMARY KEY ( ID_GRUPY ) ;


CREATE TABLE KLIENT
  (
    ID_KLIENTA               NUMBER (7) NOT NULL ,
    IMIE                     VARCHAR2 (200) ,
    NAZWISKO                 VARCHAR2 (200) ,
    GRUPA_KLIENTELI_ID_GRUPY NUMBER (7) NOT NULL
  ) ;
ALTER TABLE KLIENT ADD CONSTRAINT KLIENT_PK PRIMARY KEY ( ID_KLIENTA ) ;


CREATE TABLE KWARTAL
  (
    ID_KWARTALU NUMBER (7) NOT NULL ,
    NAZWA       VARCHAR2 (200)
  ) ;
ALTER TABLE KWARTAL ADD CONSTRAINT KWARTAL_PK PRIMARY KEY ( ID_KWARTALU ) ;


CREATE TABLE MIESIAC
  (
    ID_MIESIACA NUMBER (7) NOT NULL ,
    NAZWA       VARCHAR2 (200)
  ) ;
ALTER TABLE MIESIAC ADD CONSTRAINT MIESIAC_PK PRIMARY KEY ( ID_MIESIACA ) ;


CREATE TABLE PRACOWNIK
  (
    ID_PRACOWNIKA            NUMBER (7) NOT NULL ,
    IMIE                     VARCHAR2 (200) ,
    NAZWISKO                 VARCHAR2 (200) ,
    PESEL                    NUMBER ,
    STANOWISKO_ID_STANOWISKO NUMBER (7) NOT NULL
  ) ;
ALTER TABLE PRACOWNIK ADD CONSTRAINT PRACOWNIK_PK PRIMARY KEY ( ID_PRACOWNIKA ) ;


CREATE TABLE ROK
  ( ID_ROKU NUMBER (7) NOT NULL , NUMER NUMBER
  ) ;
ALTER TABLE ROK ADD CONSTRAINT ROK_PK PRIMARY KEY ( ID_ROKU ) ;


CREATE TABLE STANOWISKO
  (
    ID_STANOWISKO    NUMBER (7) NOT NULL ,
    NAZWA            VARCHAR2 (200) ,
    PENSJA           NUMBER (10,2) ,
    STAWKA_GODZINOWA NUMBER (10,2)
  ) ;
ALTER TABLE STANOWISKO ADD CONSTRAINT STANOWISKO_PK PRIMARY KEY ( ID_STANOWISKO ) ;


CREATE TABLE TYP_PRODUKTU
  (
    ID_TYPU NUMBER (7) NOT NULL ,
    NAZWA   VARCHAR2 (200)
  ) ;
ALTER TABLE TYP_PRODUKTU ADD CONSTRAINT TYP_PRODUKTU_PK PRIMARY KEY ( ID_TYPU ) ;


CREATE TABLE TYP_ZLECENIA
  (
    ID_TYPU              NUMBER (7) NOT NULL ,
    NAZWA                VARCHAR2 (200) ,
    TYP_PRODUKTU_ID_TYPU NUMBER (7) NOT NULL
  ) ;
ALTER TABLE TYP_ZLECENIA ADD CONSTRAINT TYP_ZLECENIA_PK PRIMARY KEY ( ID_TYPU ) ;


CREATE TABLE ZLECENIE
  (
    ID_ZLECENIA             NUMBER (7) NOT NULL ,
    DATA_ID_DATY            NUMBER (7) NOT NULL ,
    TYP_ZLECENIA_ID_TYPU    NUMBER (7) NOT NULL ,
    KLIENT_ID_KLIENTA       NUMBER (7) NOT NULL ,
    PRACOWNIK_ID_PRACOWNIKA NUMBER (7) NOT NULL ,
    CENA_USLUGI             NUMBER (10,2) ,
    KOSZT_MATERIALOW        NUMBER (10,2) ,
    ZYSK                    NUMBER (10,2) ,
    CZAS_TRWANIA            NUMBER
  ) ;
ALTER TABLE ZLECENIE ADD CONSTRAINT ZLECENIE_PK PRIMARY KEY ( ID_ZLECENIA ) ;


ALTER TABLE DATA ADD CONSTRAINT DATA_DZIEN_TYGODNIA_FK FOREIGN KEY ( DZIEN_TYGODNIA_ID_DNIA ) REFERENCES DZIEN_TYGODNIA ( ID_DNIA ) ;

ALTER TABLE DATA ADD CONSTRAINT DATA_KWARTAL_FK FOREIGN KEY ( KWARTAL_ID_KWARTALU ) REFERENCES KWARTAL ( ID_KWARTALU ) ;

ALTER TABLE DATA ADD CONSTRAINT DATA_MIESIAC_FK FOREIGN KEY ( MIESIAC_ID_MIESIACA ) REFERENCES MIESIAC ( ID_MIESIACA ) ;

ALTER TABLE DATA ADD CONSTRAINT DATA_ROK_FK FOREIGN KEY ( ROK_ID_ROKU ) REFERENCES ROK ( ID_ROKU ) ;

ALTER TABLE KLIENT ADD CONSTRAINT KLIENT_GRUPA_KLIENTELI_FK FOREIGN KEY ( GRUPA_KLIENTELI_ID_GRUPY ) REFERENCES GRUPA_KLIENTELI ( ID_GRUPY ) ;

ALTER TABLE PRACOWNIK ADD CONSTRAINT PRACOWNIK_STANOWISKO_FK FOREIGN KEY ( STANOWISKO_ID_STANOWISKO ) REFERENCES STANOWISKO ( ID_STANOWISKO ) ;

ALTER TABLE TYP_ZLECENIA ADD CONSTRAINT TYP_ZLECENIA_TYP_PRODUKTU_FK FOREIGN KEY ( TYP_PRODUKTU_ID_TYPU ) REFERENCES TYP_PRODUKTU ( ID_TYPU ) ;

ALTER TABLE ZLECENIE ADD CONSTRAINT ZLECENIE_DATA_FK FOREIGN KEY ( DATA_ID_DATY ) REFERENCES DATA ( ID_DATY ) ;

ALTER TABLE ZLECENIE ADD CONSTRAINT ZLECENIE_KLIENT_FK FOREIGN KEY ( KLIENT_ID_KLIENTA ) REFERENCES KLIENT ( ID_KLIENTA ) ;

ALTER TABLE ZLECENIE ADD CONSTRAINT ZLECENIE_PRACOWNIK_FK FOREIGN KEY ( PRACOWNIK_ID_PRACOWNIKA ) REFERENCES PRACOWNIK ( ID_PRACOWNIKA ) ;

ALTER TABLE ZLECENIE ADD CONSTRAINT ZLECENIE_TYP_ZLECENIA_FK FOREIGN KEY ( TYP_ZLECENIA_ID_TYPU ) REFERENCES TYP_ZLECENIA ( ID_TYPU ) ;

