load data
infile 'zlecenie.csv'
append into table ZLECENIE
fields terminated by ','
(ID_ZLECENIA,DATA_ID_DATY,TYP_ZLECENIA_ID_TYPU,KLIENT_ID_KLIENTA,PRACOWNIK_ID_PRACOWNIKA,CENA_USLUGI "TO_NUMBER(:CENA_USLUGI,'999999.99')",KOSZT_MATERIALOW "TO_NUMBER(:KOSZT_MATERIALOW,'999999.99')",
ZYSK "TO_NUMBER(:ZYSK,'999999.99')",CZAS_TRWANIA)